{
  "name": "Teste",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-GB",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "sales",
        "lineageTag": "7af71bc8-5441-4746-8100-c09b11875e8b",
        "columns": [
          {
            "name": "OrderKey",
            "dataType": "int64",
            "sourceColumn": "OrderKey",
            "formatString": "0",
            "lineageTag": "9ab41a35-8784-4c97-ae3f-467bd9879eb0",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "LineNumber",
            "dataType": "int64",
            "sourceColumn": "LineNumber",
            "formatString": "0",
            "lineageTag": "7237b618-d502-487f-8180-4da551c380aa",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "formatString": "Long Date",
            "lineageTag": "b0742644-00f7-4dbd-b617-bf6eab9724eb",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "bbe79273-b77a-44e0-bc44-9be187567647",
                "defaultHierarchy": {
                  "table": "LocalDateTable_74245ee0-c7ec-4580-8810-44f9e0e8b8bd",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "DeliveryDate",
            "dataType": "dateTime",
            "sourceColumn": "DeliveryDate",
            "formatString": "Long Date",
            "lineageTag": "65d28ebd-93c6-49a5-b233-c4d0a5713214",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey",
            "formatString": "0",
            "lineageTag": "4b0f77e5-5905-41a5-a13d-2ac63383cb24",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey",
            "formatString": "0",
            "lineageTag": "66604ea8-44b9-4aa6-9294-766f8ee62a87",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey",
            "formatString": "0",
            "lineageTag": "5be0aac3-a2c3-4efd-94c1-c3013c06592b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity",
            "formatString": "0",
            "lineageTag": "1d5b4ad9-8bf4-46a4-82c0-e092fc0fccf5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "sourceColumn": "UnitPrice",
            "lineageTag": "7bc9a204-1f73-4714-97b2-9b05bb5a48d2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "NetPrice",
            "dataType": "double",
            "sourceColumn": "NetPrice",
            "lineageTag": "9ac44696-9f90-40c6-b73b-0801442521d6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "UnitCost",
            "dataType": "double",
            "sourceColumn": "UnitCost",
            "lineageTag": "7fb81d7e-310f-404a-8f61-e884f63875c3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "CurrencyCode",
            "dataType": "string",
            "sourceColumn": "CurrencyCode",
            "lineageTag": "27edafba-5f16-4f71-9749-83f8cb19830e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ExchangeRate",
            "dataType": "double",
            "sourceColumn": "ExchangeRate",
            "lineageTag": "9bc3c09d-31bc-47dc-80ff-67285e3bc0fa",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "sales",
            "mode": "import",
            "queryGroup": "Transform",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "",
                "    Source = Tables,",
                "    Filtered_Rows = ",
                "        Table.SelectRows(",
                "            Source, ",
                "            each ([Name] = \"sales.csv\")",
                "        ),",
                "    #\"Removed Columns\" = Table.RemoveColumns(Filtered_Rows,{\"Content\", \"Name\"}),",
                "    #\"Expanded Binary_to_table\" = Table.ExpandTableColumn(#\"Removed Columns\", \"Binary_to_table\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Expanded Binary_to_table\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"OrderKey\", Int64.Type}, {\"LineNumber\", Int64.Type}, {\"OrderDate\", type date}, {\"DeliveryDate\", type date}, {\"CustomerKey\", Int64.Type}, {\"StoreKey\", Int64.Type}, {\"ProductKey\", Int64.Type}, {\"Quantity\", Int64.Type}, {\"UnitPrice\", type number}, {\"NetPrice\", type number}, {\"UnitCost\", type number}, {\"CurrencyCode\", type text}, {\"ExchangeRate\", type number}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sales Amount",
            "expression": [
              "",
              "VAR",
              "    TotalSales =",
              "        SUMX(",
              "            Sales,",
              "            Sales[Quantity] * Sales[NetPrice]",
              "        )",
              "RETURN",
              "    TotalSales",
              "    "
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Key Measures",
            "lineageTag": "2c3accbc-0976-48fd-ad3a-8667a1f55a3f"
          },
          {
            "name": "Total Cost",
            "expression": [
              "",
              "SUMX(",
              "    Sales,",
              "    Sales[Quantity] * Sales[UnitCost]",
              ")",
              "    "
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Key Measures",
            "lineageTag": "fb25c945-3b5b-4781-9073-b803119e0e5b"
          },
          {
            "name": "Margin",
            "expression": "[Sales Amount] - [Total Cost]",
            "formatString": "#,##0.00",
            "displayFolder": "Key Measures",
            "lineageTag": "6541cbc1-ddd7-4b9e-9250-b64570b4a546"
          },
          {
            "name": "Margin %",
            "expression": [
              "",
              "DIVIDE(",
              "    [Margin],",
              "    [Sales Amount]",
              ")",
              "    "
            ],
            "formatString": "0.00 %",
            "displayFolder": "Key Measures",
            "lineageTag": "fd81e115-620b-4208-ae68-15d37c5e697a"
          },
          {
            "name": "Total Quantity",
            "expression": "SUM( Sales[Quantity] )",
            "formatString": "#,##0",
            "displayFolder": "Key Measures",
            "lineageTag": "14d3ea8f-450e-4a4f-a2a4-5f2c49b350c8"
          },
          {
            "name": "Order Count",
            "expression": "DISTINCTCOUNT( Sales[OrderKey] )",
            "formatString": "#,##0",
            "displayFolder": "Key Measures",
            "lineageTag": "421a36ce-944c-44ef-8835-6cecf1754398"
          },
          {
            "name": "Sales YTD",
            "expression": [
              "",
              "TOTALYTD(",
              "    [Sales Amount],",
              "    'Date'[Date]",
              ")",
              "    "
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Key Measures",
            "lineageTag": "30f91d03-0c3a-4424-a92d-2508749f66d6"
          },
          {
            "name": "Sales PY",
            "expression": [
              "",
              "CALCULATE(",
              "    [Sales Amount],",
              "    SAMEPERIODLASTYEAR( 'Date'[Date] )",
              ")",
              "    "
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Key Measures",
            "lineageTag": "c15bd870-2b47-418d-a310-62d1bae6ba17"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DateTableTemplate_0ac2ff7b-ea6d-438f-9cb0-6de9793b7b65",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "d1563fb6-c0da-4422-9c2a-001ced4d3da9",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "233b620f-e51b-494a-bfa6-fda3166d3d2f",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "ff21f38b-07c0-4c46-9e2a-72f8be3f76b8",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "f3312fd9-cab4-4a25-bf86-360101538f53",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "3ab6ed56-8bfd-4990-9395-6c901b252753",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "58cb3231-2ba7-46bb-8fd1-40864101711f",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "d8ffe4a6-2a31-47ca-9a93-26e432cd2e59",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "2fd2143d-e303-4fc3-85c5-3d7bf82d45a0",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_0ac2ff7b-ea6d-438f-9cb0-6de9793b7b65",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "58585523-2456-423f-8ca0-024b9808d60f",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "f18557d7-4ffe-429c-bc48-7c90dd0eb97c"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "770e6add-56e7-4c51-979a-a2aa56033193"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "c3f4f942-bfa5-4f56-a833-5d65bdf0cce3"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "e35c39b3-94a9-4453-91f2-0d8b741f43b8"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "LocalDateTable_74245ee0-c7ec-4580-8810-44f9e0e8b8bd",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "60e348cc-f635-4719-90d6-b2eb90af1e43",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "9b0f20ff-9051-4260-9f17-6e40441928b3",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "cc14e4df-d503-48b8-9350-0603ce2212bc",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "b3dcbbdf-ab37-48cd-8ff1-5a3e1c6827e8",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "a09b7f56-a70c-4d9d-9da1-0d26c7b8d438",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "ccacc06f-d696-40f4-b45e-fe0c76e05cd5",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "13f6aba3-f2cb-4462-ad14-030e8f59e15d",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "10229b2a-1bb6-40da-8176-b61ef5d5f1d9",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_74245ee0-c7ec-4580-8810-44f9e0e8b8bd",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('sales'[OrderDate])), 1, 1), Date(Year(MAX('sales'[OrderDate])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "386143ce-ef21-4dfd-8a08-0840c1f1e493",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "6b5fb8e1-3256-4618-90ca-351554cede32"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "c42d957d-7b93-4da8-86e8-a7bdec4d058b"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "ebbce712-b29f-4268-ad0b-8a2f429d0253"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "a5709400-32c1-4c19-9939-84192523a5a4"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "customer",
        "lineageTag": "5dbe950c-fbd0-4530-a67f-8430ae5e0b84",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey",
            "formatString": "0",
            "lineageTag": "35f6892a-63ab-4648-b2b2-ad8ce3d03b51",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GeoAreaKey",
            "dataType": "int64",
            "sourceColumn": "GeoAreaKey",
            "formatString": "0",
            "lineageTag": "19f004dc-25ca-462b-b44d-376b45889592",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StartDT",
            "dataType": "dateTime",
            "sourceColumn": "StartDT",
            "formatString": "Long Date",
            "lineageTag": "a7a02885-1cca-433c-bd78-0b8ed683b470",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "a51408ed-6725-404e-8d33-a2354b762a5c",
                "defaultHierarchy": {
                  "table": "LocalDateTable_b0e4995f-d837-4f31-ba1e-62a51de5a074",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "EndDT",
            "dataType": "dateTime",
            "sourceColumn": "EndDT",
            "formatString": "Long Date",
            "lineageTag": "b178bd4f-67ca-473f-9b1e-5c7c1aa156c0",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "b3e8baa7-6a69-47f3-ad15-b75df5471f26",
                "defaultHierarchy": {
                  "table": "LocalDateTable_b1cbe7d7-a38c-468b-afb6-e9e8916f0e61",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent",
            "lineageTag": "11a15f7c-1172-4782-bfc5-bf31f80fe3ee",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "lineageTag": "ccd486f2-2867-453d-b6fc-cd2d7e37e188",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title",
            "lineageTag": "19d3b45b-875a-461d-99b8-8c599be4f2c4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GivenName",
            "dataType": "string",
            "sourceColumn": "GivenName",
            "lineageTag": "8bd9281a-3620-4030-bdfb-783f361a9d9a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MiddleInitial",
            "dataType": "string",
            "sourceColumn": "MiddleInitial",
            "lineageTag": "6b0e9233-3283-47e4-a3f1-eb1e5d4ba78d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Surname",
            "dataType": "string",
            "sourceColumn": "Surname",
            "lineageTag": "6eb4813f-c88b-4511-900d-c2579759a4ec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StreetAddress",
            "dataType": "string",
            "sourceColumn": "StreetAddress",
            "lineageTag": "a92db516-ed9b-40d2-89f1-47dca0dc251c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "ba0f0b3e-8e72-4840-9593-fd70bcd18700",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "d757bce5-1e9a-4523-870d-962499e24683",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StateFull",
            "dataType": "string",
            "sourceColumn": "StateFull",
            "lineageTag": "96231a66-31e9-4b11-8cd0-8f244ea825f9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ZipCode",
            "dataType": "string",
            "sourceColumn": "ZipCode",
            "lineageTag": "827bda18-7ce1-4328-8e26-f4aecfa7a990",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "lineageTag": "795a2777-c69c-4a86-bebb-d0560be966da",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CountryFull",
            "dataType": "string",
            "sourceColumn": "CountryFull",
            "lineageTag": "04f76124-6ffb-44e1-8559-0cc86d6eae8c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Birthday",
            "dataType": "dateTime",
            "sourceColumn": "Birthday",
            "formatString": "Long Date",
            "lineageTag": "409a3a29-5c51-4b6b-be10-6a05a5c2830e",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "2b185df4-7334-43f8-8724-7767a96238e5",
                "defaultHierarchy": {
                  "table": "LocalDateTable_7f53f1c5-232c-4185-8eab-3beb0eaa08b1",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Age",
            "dataType": "int64",
            "sourceColumn": "Age",
            "formatString": "0",
            "lineageTag": "72580cf6-5969-47f1-918a-87600f1b8666",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Occupation",
            "dataType": "string",
            "sourceColumn": "Occupation",
            "lineageTag": "e03f46ce-925a-4113-bb49-52b7460f9414",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Company",
            "dataType": "string",
            "sourceColumn": "Company",
            "lineageTag": "ab1187eb-a079-492a-8ecf-682d5399b990",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Vehicle",
            "dataType": "string",
            "sourceColumn": "Vehicle",
            "lineageTag": "ff162207-5c9d-4bcb-816c-6392374706e2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Latitude",
            "dataType": "double",
            "sourceColumn": "Latitude",
            "lineageTag": "edb80352-0c35-4a02-b793-e4dcf5af3c52",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Longitude",
            "dataType": "double",
            "sourceColumn": "Longitude",
            "lineageTag": "9383a082-2b34-4ffc-999e-f4feb9f83c45",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "customer",
            "mode": "import",
            "queryGroup": "Transform",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "",
                "    Source = Tables,",
                "    Filtered_Rows = ",
                "        Table.SelectRows(",
                "            Source, ",
                "            each ([Name] = \"customer.csv\")",
                "        ),",
                "    #\"Removed Columns\" = Table.RemoveColumns(Filtered_Rows,{\"Content\", \"Name\"}),",
                "    #\"Expanded Binary_to_table\" = Table.ExpandTableColumn(#\"Removed Columns\", \"Binary_to_table\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Expanded Binary_to_table\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerKey\", Int64.Type}, {\"GeoAreaKey\", Int64.Type}, {\"StartDT\", type date}, {\"EndDT\", type date}, {\"Continent\", type text}, {\"Gender\", type text}, {\"Title\", type text}, {\"GivenName\", type text}, {\"MiddleInitial\", type text}, {\"Surname\", type text}, {\"StreetAddress\", type text}, {\"City\", type text}, {\"State\", type text}, {\"StateFull\", type text}, {\"ZipCode\", type text}, {\"Country\", type text}, {\"CountryFull\", type text}, {\"Birthday\", type date}, {\"Age\", Int64.Type}, {\"Occupation\", type text}, {\"Company\", type text}, {\"Vehicle\", type text}, {\"Latitude\", type number}, {\"Longitude\", type number}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_b0e4995f-d837-4f31-ba1e-62a51de5a074",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "bc80fb22-df7f-43fa-a417-057659100f79",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "1f499e5a-7ff4-40be-afa9-9d08c1d49e91",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "6c9a1d75-b2f5-405d-b01f-22fb8857af51",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "94f457bc-e1d7-4926-a861-bd797a4b9335",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "b2859d46-6455-415c-a142-dd7092d8b33e",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "f54efafa-422d-44d8-8f8a-6240c33f5b51",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "5197f340-e17c-40bf-a963-e5f6a6dd5d8d",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "76c12df5-143a-4504-bc1e-0bf91f279ffd",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_b0e4995f-d837-4f31-ba1e-62a51de5a074",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('customer'[StartDT])), 1, 1), Date(Year(MAX('customer'[StartDT])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "1d55ad60-3249-43c2-8b00-cde3b45bbb8b",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "207efffb-6618-4e74-8f14-cfadfefeb991"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "7c362361-df67-492f-804b-cce40ace4161"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "c0afd730-31fc-41f4-9afb-42d96b669982"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "3a4d0c3c-f0a4-4f7e-82c1-7a89573bb846"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_b1cbe7d7-a38c-468b-afb6-e9e8916f0e61",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "bca469dd-d10b-4e25-9cd6-495d2168a5e7",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "a8b00e42-e84b-44f2-b645-5d710e3114fd",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "d840ce1f-9a65-4df5-b238-ee41aa5eb557",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "3ae67851-8a50-49e3-9e61-f4d38ea8554a",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "547c3f43-0b63-4b8f-ae18-113dd3dcf9a4",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "93b85807-53e3-43df-bcd3-176f8ec5a9b1",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "891289b6-4eb8-4698-b5d5-7b4f7f0f271f",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "70ca294d-c89a-4608-a7d1-43eede6a5ae7",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_b1cbe7d7-a38c-468b-afb6-e9e8916f0e61",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('customer'[EndDT])), 1, 1), Date(Year(MAX('customer'[EndDT])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "efc95496-fb6e-4c6e-87e6-de0edb8227d7",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "659ea561-2f51-48cb-9d5c-ed71fd197aa4"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "1dc680e8-d9cf-46b6-9df8-91329ea46908"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "be03e9e4-22bc-49bd-924c-c02696cc4747"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "32013492-43a1-4679-927b-b2f35c8bcc73"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_7f53f1c5-232c-4185-8eab-3beb0eaa08b1",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "45126149-9f86-4b59-aa7a-832a872622f1",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "3eec19b4-a2c1-4d27-a715-c628a161db86",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "fa9daa42-c85d-4390-87a6-402b0f82168a",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "ad0f1681-8fc3-4aa9-9abf-b426a5b45d0f",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "5109e96b-140a-4a6f-83a9-e757e97f5ec0",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "26fa9d83-4904-487c-9cbd-49921d7f269c",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "2776401c-43f7-4829-9042-7c124b711609",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "246ab802-3d12-4615-ab0c-9e45b1fa36ff",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_7f53f1c5-232c-4185-8eab-3beb0eaa08b1",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('customer'[Birthday])), 1, 1), Date(Year(MAX('customer'[Birthday])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "8b3748ff-4faa-43a6-9a3f-dff99ff5c33e",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "34d32260-1503-4a0d-9383-825458074b8f"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "4306b9df-9ede-44eb-bb82-f073ea8ce4e9"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "bba03ce4-c321-4986-9e56-fe2f0c3fc249"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "57376e9a-3323-4a16-bc36-e2eacb654574"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "product",
        "lineageTag": "c05f9b18-38a9-4a87-8403-4cce259446c5",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey",
            "formatString": "0",
            "lineageTag": "e0d46537-cc3c-4371-bbd9-b014c156e59b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductCode",
            "dataType": "int64",
            "sourceColumn": "ProductCode",
            "formatString": "0",
            "lineageTag": "5d0464d6-3635-4ff8-9d84-339fba9902ff",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName",
            "lineageTag": "4a6af473-be16-4ef8-8208-b83aca551184",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Manufacturer",
            "dataType": "string",
            "sourceColumn": "Manufacturer",
            "lineageTag": "e2d207da-ad77-4cc0-b14a-8d35a1b5a5e9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "lineageTag": "bbe30964-fd0b-4fa7-a5a5-37b581b7434b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color",
            "lineageTag": "d6f04371-30d4-4508-ad96-c597c076019f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "WeightUnit",
            "dataType": "string",
            "sourceColumn": "WeightUnit",
            "lineageTag": "de7e55bb-058a-49d5-8fe3-40251eaf650a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight",
            "lineageTag": "80a9d33a-54d4-42bb-8aea-f82287980649",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Cost",
            "dataType": "double",
            "sourceColumn": "Cost",
            "lineageTag": "264c55ab-2137-4d53-9b59-d3fc8bfd8193",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Price",
            "dataType": "double",
            "sourceColumn": "Price",
            "lineageTag": "e9d9baea-d93d-4089-8652-df77a1993c27",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "CategoryKey",
            "dataType": "int64",
            "sourceColumn": "CategoryKey",
            "formatString": "0",
            "lineageTag": "b71b9e5f-a9af-4f3a-8a38-d233cb95713a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CategoryName",
            "dataType": "string",
            "sourceColumn": "CategoryName",
            "lineageTag": "6726827e-afb7-4d8c-9497-9b44c63f361b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SubCategoryKey",
            "dataType": "int64",
            "sourceColumn": "SubCategoryKey",
            "formatString": "0",
            "lineageTag": "97b81b9c-c7b5-4aae-8456-1a33f02898a9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SubCategoryName",
            "dataType": "string",
            "sourceColumn": "SubCategoryName",
            "lineageTag": "e1c3b90d-b114-4479-ae4e-88a5deb88bf4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "product",
            "mode": "import",
            "queryGroup": "Transform",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "",
                "    Source = Tables,",
                "    Filtered_Rows = ",
                "        Table.SelectRows(",
                "            Source, ",
                "            each ([Name] = \"product.csv\")",
                "        ),",
                "    #\"Removed Columns\" = Table.RemoveColumns(Filtered_Rows,{\"Content\", \"Name\"}),",
                "    #\"Expanded Binary_to_table\" = Table.ExpandTableColumn(#\"Removed Columns\", \"Binary_to_table\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Expanded Binary_to_table\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductKey\", Int64.Type}, {\"ProductCode\", Int64.Type}, {\"ProductName\", type text}, {\"Manufacturer\", type text}, {\"Brand\", type text}, {\"Color\", type text}, {\"WeightUnit\", type text}, {\"Weight\", type number}, {\"Cost\", type number}, {\"Price\", type number}, {\"CategoryKey\", Int64.Type}, {\"CategoryName\", type text}, {\"SubCategoryKey\", Int64.Type}, {\"SubCategoryName\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "store",
        "lineageTag": "d913e275-f6ea-4b32-b36f-3e4278c7e305",
        "columns": [
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey",
            "formatString": "0",
            "lineageTag": "bb2e4995-89d8-4cf8-b5fe-65ad990d678c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StoreCode",
            "dataType": "int64",
            "sourceColumn": "StoreCode",
            "formatString": "0",
            "lineageTag": "3e580865-38d1-4802-b34e-0c0554823e33",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GeoAreaKey",
            "dataType": "int64",
            "sourceColumn": "GeoAreaKey",
            "formatString": "0",
            "lineageTag": "e45a4951-7e3c-4e77-b8a1-b5f2f51d9c1b",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CountryCode",
            "dataType": "string",
            "sourceColumn": "CountryCode",
            "lineageTag": "d0504edd-325d-4572-aeb9-ea732d4c73b5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CountryName",
            "dataType": "string",
            "sourceColumn": "CountryName",
            "lineageTag": "84105127-b2f0-419c-a908-14ac2b10512f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "ab615b2f-3fe2-4324-b5dd-7241f948c0d1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OpenDate",
            "dataType": "dateTime",
            "sourceColumn": "OpenDate",
            "formatString": "Long Date",
            "lineageTag": "087324db-411b-4b64-b724-7bc72148f601",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "80199e24-20be-4d7a-8ed0-0e4c2911bcfd",
                "defaultHierarchy": {
                  "table": "LocalDateTable_cd8299c7-ab5d-4ed8-86f0-d0071b623ba2",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "CloseDate",
            "dataType": "dateTime",
            "sourceColumn": "CloseDate",
            "formatString": "Long Date",
            "lineageTag": "c887b5b3-c44f-4242-973d-938ae89feca5",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "b0f75f98-a8c9-41b2-aca6-3e712a56675d",
                "defaultHierarchy": {
                  "table": "LocalDateTable_32c872a2-ee5f-4a2a-90a8-4701412ad437",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "1070bdf0-9ce2-4db4-aab3-f04f14bc3c68",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SquareMeters",
            "dataType": "int64",
            "sourceColumn": "SquareMeters",
            "formatString": "0",
            "lineageTag": "3952bdbb-5f9a-4683-9571-6ab67c7aacf5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "lineageTag": "a1234f6a-6151-415e-80e6-b3838a4f653a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "store",
            "mode": "import",
            "queryGroup": "Transform",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "",
                "    Source = Tables,",
                "    Filtered_Rows = ",
                "        Table.SelectRows(",
                "            Source, ",
                "            each ([Name] = \"store.csv\")",
                "        ),",
                "    #\"Removed Columns\" = Table.RemoveColumns(Filtered_Rows,{\"Content\", \"Name\"}),",
                "    #\"Expanded Binary_to_table\" = Table.ExpandTableColumn(#\"Removed Columns\", \"Binary_to_table\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Expanded Binary_to_table\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"StoreKey\", Int64.Type}, {\"StoreCode\", Int64.Type}, {\"GeoAreaKey\", Int64.Type}, {\"CountryCode\", type text}, {\"CountryName\", type text}, {\"State\", type text}, {\"OpenDate\", type date}, {\"CloseDate\", type date}, {\"Description\", type text}, {\"SquareMeters\", Int64.Type}, {\"Status\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_cd8299c7-ab5d-4ed8-86f0-d0071b623ba2",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "48b01dbb-0880-4293-818f-5d07d438f1cc",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "a59957a5-4e99-4cdd-8071-4574dceccdd3",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "51879138-62dc-4606-910d-6101e6b20054",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "9d1a4686-6ce1-4e75-a0fa-bd6fc0309cd5",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "8acb20ac-4554-4d85-94b3-79878b87e26d",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "b036bc5e-0924-4834-9593-b74c800da040",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "684cf95f-1597-4100-ba51-f7d5cbd3e844",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "7e9da003-8162-4942-aa82-41334d13fedc",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_cd8299c7-ab5d-4ed8-86f0-d0071b623ba2",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('store'[OpenDate])), 1, 1), Date(Year(MAX('store'[OpenDate])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "3209c203-e8c7-438c-b6f1-4886493ec2c8",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "1eff6570-1b54-4536-bc15-55c2a98309e5"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "284001d7-161f-4232-afa7-3e1b3b91b8d4"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "7dbcf829-4db8-4645-a51e-90eec086dbc1"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "418bbd70-e131-4459-bff1-683f9bd3d9fe"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_32c872a2-ee5f-4a2a-90a8-4701412ad437",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "f68d50b5-fe79-44d1-be6e-8051b02c9966",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "92a9179d-bc2b-452f-8f82-90e9c539ac92",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "c4e5cbb6-2442-46ee-96c7-ca41d7eb06bb",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "4ac31ad8-05fa-4e69-b87b-7dd635f7217d",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "625d07fe-6f66-4139-ab02-281916ab4fe2",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "1e44d53a-ee6a-4a96-8df0-aa6aacacb487",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "2b909bdd-10c1-43ac-8cf8-74cc75cbbc37",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "0b5c6109-7de5-4719-b090-ff8ab6816356",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_32c872a2-ee5f-4a2a-90a8-4701412ad437",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('store'[CloseDate])), 1, 1), Date(Year(MAX('store'[CloseDate])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "1a226477-4f2b-4776-8e13-b29d100cecee",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "5c573be3-b42d-45fb-9381-c52c518f5b57"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "abd97bd3-9642-4cde-829a-4f5f6332b5b3"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "68812d01-f644-450a-b699-5172649c1f65"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "2da2ce5e-80bb-4d53-afff-f061efdea3aa"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "089b651b-b154-4297-98ac-dcda15886736",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isKey": true,
            "sourceColumn": "[Date]",
            "lineageTag": "447e99e4-51cb-4961-aebe-4ee506894e95",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DateKey",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[DateKey]",
            "lineageTag": "4edd251f-6b3d-4eb9-a6d8-b4f096fbda05",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Year]",
            "lineageTag": "7eaf4f22-368c-4291-8707-4cca5919b0c1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "QuarterNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[QuarterNumber]",
            "lineageTag": "3b10c431-4544-4575-8ab9-602912e43406",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Quarter]",
            "lineageTag": "d247ddd8-b697-4788-b484-f98a3a478690",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "YearQuarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[YearQuarter]",
            "lineageTag": "02b4896e-786b-403a-8c4e-5e3ed8e79fa5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "YearQuarterSort",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[YearQuarterSort]",
            "lineageTag": "54dacec6-c2b0-4b70-bb8d-e69e2de8f2c4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[MonthNumber]",
            "lineageTag": "fd3bf679-e451-4c77-9e35-0622f81671d6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[MonthName]",
            "sortByColumn": "MonthNumber",
            "lineageTag": "9723fca3-61fe-4c41-96d3-4f7ed08d88d1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthNameShort",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[MonthNameShort]",
            "sortByColumn": "MonthNumber",
            "lineageTag": "e0b9ea9a-2bd2-47db-a65c-2a3cc37d0a77",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "YearMonth",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[YearMonth]",
            "lineageTag": "da122646-ecae-4fac-85f7-f23b46d317cb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DayOfMonth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[DayOfMonth]",
            "lineageTag": "c185a080-6e01-4ce2-8146-775d85f98d55",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DayOfWeekNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[DayOfWeekNumber]",
            "lineageTag": "4a6afaf8-40ca-43f8-86b0-d58c4f247ea6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DayOfWeekName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[DayOfWeekName]",
            "lineageTag": "d23a364e-7f98-4058-95d1-834c970d36fd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DayOfWeekNameShort",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[DayOfWeekNameShort]",
            "lineageTag": "3740747b-f0c6-4e91-99eb-d3290c7691b1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "New Calculated Table",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "VAR",
                "    MinDate = MIN( Sales[OrderDate] )",
                "VAR",
                "    MaxDate = MAX( Sales[OrderDate] )",
                "VAR",
                "    BaseCalendar =",
                "        CALENDAR( MinDate, MaxDate )",
                "RETURN",
                "    ADDCOLUMNS (",
                "        BaseCalendar,",
                "        \"DateKey\", FORMAT( [Date], \"yyyyMMdd\" ), ",
                "        \"Year\", YEAR( [Date] ),",
                "        \"QuarterNumber\", QUARTER( [Date] ),",
                "        \"Quarter\", \"Q\" & QUARTER( [Date] ),",
                "        \"YearQuarter\", FORMAT( [Date], \"yyyy\" ) & \"-Q\" & QUARTER( [Date] ),",
                "        \"YearQuarterSort\", FORMAT( [Date], \"yyyy\" ) & QUARTER( [Date] ),",
                "        \"MonthNumber\", MONTH( [Date] ),",
                "        \"MonthName\", FORMAT( [Date], \"mmmm\" ),",
                "        \"MonthNameShort\", FORMAT( [Date], \"mmm\" ),",
                "        \"YearMonth\", FORMAT( [Date], \"yyyy-mm\" ),",
                "        \"DayOfMonth\", DAY( [Date] ),",
                "        \"DayOfWeekNumber\", WEEKDAY( [Date], 2 ),",
                "        \"DayOfWeekName\", FORMAT( [Date], \"dddd\" ),",
                "        \"DayOfWeekNameShort\", FORMAT( [Date], \"ddd\" )",
                "    )"
              ]
            }
          }
        ]
      },
      {
        "name": "Time",
        "lineageTag": "7b631020-4147-4aa5-9067-13ef936b6d27",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Current",
              "expression": "SELECTEDMEASURE()",
              "ordinal": 0
            },
            {
              "name": "Year-to-Date",
              "expression": [
                "TOTALYTD(",
                "    SELECTEDMEASURE(),",
                "    'Date'[Date]",
                ")"
              ],
              "ordinal": 2
            },
            {
              "name": "Preview year",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    SAMEPERIODLASTYEAR( 'Date'[Date] )",
                ")"
              ],
              "ordinal": 1
            }
          ]
        },
        "columns": [
          {
            "name": "Time Calculation",
            "dataType": "string",
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "bc253023-b029-40e0-974e-b97bfe6daf98"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "lineageTag": "5f1f884c-3b14-40c8-8c81-59057c785a96"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "bbe79273-b77a-44e0-bc44-9be187567647",
        "fromTable": "sales",
        "fromColumn": "OrderDate",
        "toTable": "LocalDateTable_74245ee0-c7ec-4580-8810-44f9e0e8b8bd",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "a51408ed-6725-404e-8d33-a2354b762a5c",
        "fromTable": "customer",
        "fromColumn": "StartDT",
        "toTable": "LocalDateTable_b0e4995f-d837-4f31-ba1e-62a51de5a074",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "b3e8baa7-6a69-47f3-ad15-b75df5471f26",
        "fromTable": "customer",
        "fromColumn": "EndDT",
        "toTable": "LocalDateTable_b1cbe7d7-a38c-468b-afb6-e9e8916f0e61",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "2b185df4-7334-43f8-8724-7767a96238e5",
        "fromTable": "customer",
        "fromColumn": "Birthday",
        "toTable": "LocalDateTable_7f53f1c5-232c-4185-8eab-3beb0eaa08b1",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "80199e24-20be-4d7a-8ed0-0e4c2911bcfd",
        "fromTable": "store",
        "fromColumn": "OpenDate",
        "toTable": "LocalDateTable_cd8299c7-ab5d-4ed8-86f0-d0071b623ba2",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "b0f75f98-a8c9-41b2-aca6-3e712a56675d",
        "fromTable": "store",
        "fromColumn": "CloseDate",
        "toTable": "LocalDateTable_32c872a2-ee5f-4a2a-90a8-4701412ad437",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "AutoDetected_5188c8aa-a74d-42bf-88c6-66877345d02c",
        "fromTable": "sales",
        "fromColumn": "CustomerKey",
        "toTable": "customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "AutoDetected_5961dc9c-e18c-4348-bb87-5f6693e4f6fb",
        "fromTable": "sales",
        "fromColumn": "StoreKey",
        "toTable": "store",
        "toColumn": "StoreKey"
      },
      {
        "name": "AutoDetected_b1014258-d96e-4a42-bee1-b145fe5ab8ce",
        "fromTable": "sales",
        "fromColumn": "ProductKey",
        "toTable": "product",
        "toColumn": "ProductKey"
      },
      {
        "name": "83cc3d16-18e4-2066-c05c-1baa268a472d",
        "fromTable": "sales",
        "fromColumn": "DeliveryDate",
        "toTable": "Date",
        "toColumn": "Date"
      }
    ],
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US"
          },
          "contentType": "json"
        }
      }
    ],
    "roles": [
      {
        "name": "New Model Role",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "465674c262f6452e93ac586e5a3a491d"
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "csv-10k",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\Users\\leand\\Downloads\\csv-10k\\Database\")",
          "in",
          "    Source"
        ],
        "queryGroup": "Source",
        "lineageTag": "b6cc89c8-9bd8-4a98-ba34-8933288f3a04",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Tables",
        "kind": "m",
        "expression": [
          "let",
          "    Source = #\"csv-10k\",",
          "    Removed_Columns = ",
          "        Table.RemoveColumns(",
          "            Source,",
          "            {\"Extension\", \"Date accessed\", \"Date modified\", \"Date created\", \"Attributes\", \"Folder Path\"}),",
          "",
          "    To_table =",
          "        Table.AddColumn(",
          "            Removed_Columns,",
          "            \"Binary_to_table\",",
          "            each Csv.Document([Content])",
          "        ),",
          "    #\"Filtered Rows\" = Table.SelectRows(To_table, each ([Name] = \"customer.csv\" or [Name] = \"product.csv\" or [Name] = \"sales.csv\" or [Name] = \"store.csv\"))",
          "in",
          "    #\"Filtered Rows\""
        ],
        "queryGroup": "Source",
        "lineageTag": "70bd4f0e-3905-4639-a4f1-02a360344728",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "Source",
        "description": "Original base",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Transform",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"csv-10k\",\"Tables\",\"sales\",\"customer\",\"product\",\"store\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"SortArrays\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}